name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TESTCONTAINERS_RYUK_DISABLED: true
      TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: "/var/run/docker.sock"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Start Docker (for Testcontainers)
        run: sudo systemctl start docker

      - name: Check Docker version
        run: docker version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Test with Maven
        run: mvn -B clean verify