name: CI para Spring Boot con Testcontainers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Test with Maven and Testcontainers
        run: |
          ./mvnw clean verify
        env:
          DOCKER_HOST: tcp://localhost:2375
